spring.application.name=flagsentinel-demo-app

server.port=8082

spring.thymeleaf.cache=false

spring.thymeleaf.encoding=UTF-8

spring.thymeleaf.mode=HTML

logging.level.com.demo.app=DEBUG
logging.level.com.sdk=DEBUG
