spring.application.name=flagsentinel-api

# ============================
# ACTIVE PROFILE
# ============================
spring.profiles.active=dev

# ============================
# JACKSON PROPERTIES
# ============================
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss
spring.jackson.time-zone=Europe/Madrid

# ============================
# SWAGGER API-DOCS PROPERTIES
# ============================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.url=/openapi.yaml

# ============================
# ADMIN INICIAL
# ============================
app.admin.username=admin
app.admin.password=admin

