# ============================
# DATASOURCE (MySQL local)
# ============================
spring.datasource.url=jdbc:mysql://localhost:3306/flagsentinel
spring.datasource.username=root
spring.datasource.password=toor

# ============================
# JPA / HIBERNATE
# ============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ============================
# SERVER
# ============================
server.port=8080

# ============================
# LOGGING
# ============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework=TRACE

# ============================
# JWT (temporal para dev)
# ============================
jwt.secret= dev-flag-sentinel-secret-key-123456
jwt.expiration=3600000